### ISSUE TITLE
Pb with fastled-monaco while compiling

### ISSUE THREAD

**Issue by SebCanet** [arcostasi/avr8js-electron-playground#4]
Hi,
it cannot compile:

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/wokwi/fastled-monaco/fastled-monaco.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Thanks to verify.

**Comment by sutaburosu** [comment]
You must install `git` and add it to your PATH.
