### ISSUE TITLE
project not running properly

### ISSUE THREAD

**Issue by singhankush01** [arcostasi/avr8js-electron-playground#5]
![avrss](https://user-images.githubusercontent.com/44083904/159214515-97e12094-ae3b-4ca1-bbae-c551e70c1007.jpeg)
as you can see in the picture that when running the project no buttons for adding elements are appearing neither is the code editor working

**Comment by ricardojlrufino** [comment]
I have same error !

**Comment by ricardojlrufino** [comment]
![image](https://user-images.githubusercontent.com/515675/160034559-37eb13fa-8fa4-4ddd-b6f5-da0f73f5d2ca.png)

**Comment by arcostasi** [comment]
Hi @ricardojlrufino, thanks for reporting! I updated the packages and made some changes to run! Please update your clone and try running again. Note: With the new avrjs update the execution was above 100%, I will be checking in the next few days.

**Comment by ricardojlrufino** [comment]
wow !! thanks @arcostasi  !!!
its working ...
