### ISSUE TITLE
Build error npm run build

### ISSUE THREAD

**Issue by dgarridouma** [arcostasi/avr8js-electron-playground#6]
Hello,
I have followed instructions but an error is obtained when npm run build is done:

> avr8js-electron-playground@0.18.10 build
> tsc

src/app/preload.ts:24:20 - error TS2740: Type '{ red: number; green: number; blue: number; }' is missing the following properties from type 'Color': rgba, hsla, hsva, equals, and 14 more.

24     new Titlebar({ backgroundColor });
                      ~~~~~~~~~~~~~~~

  node_modules/custom-electron-titlebar/titlebar/options.d.ts:9:5
    9     backgroundColor?: Color;
          ~~~~~~~~~~~~~~~
    The expected type comes from property 'backgroundColor' which is declared here on type 'TitleBarOptions'

Found 1 error in src/app/preload.ts:24

Kind regards.

**Comment by zenglhardt** [comment]
Here's how I fixed this: 

Change line 1 of preload.ts to:
`import { Titlebar, TitlebarColor as Color} from 'custom-electron-titlebar';`

Change the line setting backgroundColor in preload.ts to:
`const backgroundColor = Color.fromHex('#444');`

Hope this helps!

**Comment by dgarridouma** [comment]
Hi, it worked perfectly!
Thank you very much

**Comment by arcostasi** [comment]
Thanks, fix made to the code!
